// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8F7t0rjEuIcQKbjKKbOoVsd1cd5Duzhs',
    appId: '1:100557735058:web:2ef4ea03e304c1c574d24b',
    messagingSenderId: '100557735058',
    projectId: 'fir-one-921b3',
    authDomain: 'fir-one-921b3.firebaseapp.com',
    storageBucket: 'fir-one-921b3.appspot.com',
    measurementId: 'G-NNPKFD3GNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aYNiK-hb25WNT7goJdaw5U5lOhWqeiA',
    appId: '1:100557735058:android:327d484026ae491174d24b',
    messagingSenderId: '100557735058',
    projectId: 'fir-one-921b3',
    storageBucket: 'fir-one-921b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzoFGdadCv8bOFzE5maeNt-0IOzFg7okc',
    appId: '1:100557735058:ios:390b371c01cbb8d374d24b',
    messagingSenderId: '100557735058',
    projectId: 'fir-one-921b3',
    storageBucket: 'fir-one-921b3.appspot.com',
    iosClientId: '100557735058-d9c4v78f89p0rluof7udarpi89if8hps.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
